#!/usr/bin/perl -w

use strict;

# This file creates the database that translates from our
# html extensions to real html.

#$Log: Makecd2html,v $
#Revision 1.12  1997/09/04 21:11:56  myoder
#Added <cd-nav>.
#
# Revision 1.11  1997/02/27  17:51:53  myoder
# Added the <movie> tag.
#
# Revision 1.10  1996/07/05  21:08:25  myoder
# Converted to lowercase filenames.
#
# Revision 1.9  1996/01/10  21:23:24  myoder
# Changed Yellowbullet.gif to yellow.gif.
#
# Revision 1.8  1995/10/17  17:55:47  myoder
# h1 heading are now centered.
#
# Revision 1.7  1995/08/21  20:11:17  myoder
# Removed <hr> from after head.
#
# Revision 1.6  1995/06/29  21:17:48  myoder
# Using CD2HTMLDTAT environment vairable.
#
# Revision 1.5  1995/06/01  19:05:28  myoder
# Turned img back on.
# Made cd-ybullet and cd-underconstruct look for the .gif files in
# the @path.
#
# Revision 1.4  1995/06/01  16:25:13  myoder
# Added full path to $db_file.
# Added die() to dbmopen().
#
# Revision 1.3  1995/06/01  11:43:38  myoder
# Added <>'s to output strings.
# Change matlab, head, foot, body, etc. to work with new cd2html
#
# Revision 1.2  1995/06/01  11:33:54  myoder
# Added ../Graphics to the gif file paths.
#
# Revision 1.1  1995/05/17  13:40:41  myoder
# Initial revision
#
my $Header = '$Header: /home/myoder/projects/SignalFirst/visible3/cdrom/support/scripts/RCS/Makecd2html,v 1.12 1997/09/04 21:11:56 myoder Exp myoder $';

my $db_file = $ENV{'CD2HTMLDATA'};
# $db_file = '/tmp/test';

my %data;
dbmopen(%data, $db_file, 0666) || die "Can't open $db_file";

$data{'!DOCTYPE'}	= " ";
$data{'html'}		= " ";

$data{'a'}		= "&anchor(%params)";
$data{'/a'}		= "</a>";
$data{'img'}		= "&img(%params)";
# $data{'img'}		= "[[Media: ";
# $data{'movie'}		= "&movie(%params)";

$data{'cd-title'}	= "<title>";
$data{'/cd-title'}	= "</title>";
# $data{'title'}		= " ";
# $data{'/title'}		= " ";

$data{'cd-eqn'}	= "<i>";
$data{'/cd-eqn'}	= "</i>";
$data{'cd-sub'}		= "<sub><small>";
$data{'/cd-sub'}	= "</small></sub>";
$data{'cd-sup'}		= "<sup><small>";
$data{'/cd-sup'}	= "</small></sup>";
$data{'cd-pi'}		= "&pi;";
$data{'cd-phi'}		= "&phi;";
$data{'cd-theta'}      	= "&theta;";
$data{'cd-omega'}      	= "&omega;";
$data{'cd-delta'}      	= "&delta;";
$data{'cd-ge'}      	= "&ge;";
$data{'cd-reg'}      	= "<sup><small>&reg;</small></sup>";

$data{'cd-box'}      	= "<span style=\"border:1px solid black;\">";
$data{'/cd-box'}      	= "</span>";

$data{'cd-h1'}		= "==";
$data{'/cd-h1'}		= "==";
$data{'cd-h2'}		= "===";
$data{'/cd-h2'}		= "===";
$data{'cd-h3'}		= "====";
$data{'/cd-h3'}		= "====";

$data{'cd-head'}	= " "; #"&head(%params)";
$data{'/cd-head'}	= " "; #"&headend(%params)";
$data{'cd-body'}	= " "; #'&body(%params)';
$data{'/cd-body'}	= " "; #"</div></div>\n<!-- End Body -->\n"; # Do nothing </foot> will end body

# $data{'cd-nav'}          = "&nav(%params)";

# $data{'cd-foot'}	= '&foot($file)';
$data{'cd-foot'}	= " ";
# $data{'/cd-foot'}	= "</body>\n</html>";
$data{'/cd-foot'}	= " ";

# $data{'cd-eqn'}		= "&eqn";
# $data{'/cd-eqn'}	= "&error";
# $data{'cd-matlab'}	= '&matlab';
# $data{'/cd-matlab'}	= "&error";
# $data{'cd-matlabname'}  = 'M<small>ATLAB</small>';
# $data{'cd-labviewname'} = 'Lab<small>VIEW</small>';
$data{'cd-libname'}     = 'dspfirst';
$data{'cd-bookname'}    = 'DSP F<small>IRST</small>';

# $data{'cd-todo'}	= '<img src="Question.gif"><big><em><strong>';
# $data{'/cd-todo'}	= "</big></em></strong>";
$data{'cd-ybullet'}	= '&img((src, "yellow.gif"))';
$data{'cd-underconstruct'} = '&img((src, "question.gif", align, absmiddle))';

# $data{'cd-labview'}     = "&labview(%params)";
# $data{'cd-dtsp-link'}     = "&dtsplink(%params)";
# $data{'/cd-dtsp-link'}     = "&dtsplinkend(%params)";
# $data{'cd-spfirst-link'}     = "&spfirstlink(%params)";
# $data{'/cd-spfirst-link'}     = "&spfirstlinkend(%params)";

if(0) {
while (my($key,$val) = each %data) {
 	print $key, ' = ', $val, "\n";
}
}

dbmclose(%data);

print "Done making $db_file\n";
