#!/usr/local/gnu/bin/perl

# This file prints the contents of a perl database.

$Header = '$Header: /database/bookcd/support/scripts/RCS/printData,v 1.2 1996/02/07 19:07:39 myoder Exp $';

# other requires
require 'getopts.pl';

# open the filename mapping database

$db_file = $ENV{'MAPPINGDATA'};

if ( ! -e $db_file . ".dir") {
	die "$0: Cannot open mapping database $db_file\n";
}
print "$db_file\n";
dbmopen(%Map, $db_file, 0666) ||
	die "Cannot open mapping database $db_file";

#$Map{'overview.html'} = 'overview.htm';
#$Map{'index.html'} = 'index.htm';
#$Map{'index2.htm'} = 'index.htm';
# Graphics mapping
#$Map{'Orangebullet.gif'} = 'orange.gif';
#$Map{'Question2.gif'} = 'ques2.gif';
#$Map{'Yellowbullet.gif'} = 'yellow.gif';
#$Map{'next_motif.gif'} = 'next.gif';
#$Map{'nextmotif_gr.gif'} = 'next_gr.gif';
#$Map{'previous_motif.gif'} = 'prev.gif';
#$Map{'previous_motif_gr.gif'} = 'prev_gr.gif';
$Map{'foot_motif.gif'} = 'foot.gif';

$print_db = 1;
if($print_db) {
	print "----------------\n";
	while (($key,$val) = each %Map) {
 		print $key, ' = ', $val, "\n";
	}
	print "----------------\n";
}	# if($print_db)
